# spring.application.name=SevenThreeBoard

spring:
  datasource:
    url: jdbc:mysql://localhost:3305/seventhreedb?useSSL=false&allowPublicKeyRetrieval=true&ServerTimezone=Asia/Seoul
    username: root
    password: alger3010
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect